# Generated by Django 2.0.2 on 2018-03-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='map_data',
            field=models.TextField(default='asd'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='movement_data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
