# Generated by Django 2.0.2 on 2018-05-07 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointBasedMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, editable=False, max_length=100, null=True)),
                ('updated_by', models.CharField(blank=True, editable=False, max_length=255, null=True)),
                ('advanced_points', models.TextField()),
                ('label_data', models.TextField()),
                ('initial_points', models.TextField()),
                ('movement_points', models.TextField()),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Map')),
            ],
            options={
                'verbose_name': 'Point Based Map',
                'verbose_name_plural': 'Point Based Maps',
                'db_table': 'point_based_map',
            },
        ),
    ]
